# This file sets up the dictionary for data management / live plotting buffer
---
Picarro Gas:
  Time (epoch): []
  Data:
    CO2: []
    CH4: []
    CO: []
    H2O: []
# Picarro Water:
#   Time (epoch): []
#   Data:
#     H2O (ppm): []
#     Delta_18_16 (%o): []
#     Delta_D_H (%o): []
Laser Distance Sensor:
  Time (epoch): []
  Data:
    Distance (cm): []
    Temperature (C): []
Abakus Particle Counter:
  Time (epoch): []
  Data:
    Total Counts: []
  Other:
    Bins: []
    Counts: []
Flowmeter:
  Time (epoch): []
  Data:
    SLI2000 (uL/min): []
    SLS1500 (mL/min): []
# Bronkhorst Pressure:
#   Time (epoch): []
#   Data:
#     Dummy key: []
# Melthead:
#   Time (epoch): []
#   Data:
#     Dummy key: []
  
